def change(old,new):
 global s
 if old not in s: raise ValueError('Missing homework patch: '+old[:90])
 s=s.replace(old,new)
change('function prevHomework(l) {', 'function prevHomework(l, sid) {')
change(".filter(x => key(x) < key(l))", ".filter(x => key(x) < key(l) && Object.values(x.marks || {}).some(m => m.s === 'был'))")
change(".sort((a, b) => key(a) < key(b) ? 1 : -1);", ".filter(x => !sid || x.marks?.[sid]?.s === 'был')\n    .sort((a, b) => key(a) < key(b) ? 1 : -1);")
change("return mine.find(x => (x.homework || '').trim()) || null;", "return mine.find(x => (sid ? homeworkFor(x, sid) : x.homework || Object.values(x.per || {}).map(p => p.homework || '').join('')).trim()) || null;")
change('function passedTopics(type, id) {', 'function passedTopics(type, id, sid) {')
change('l.topicId && isMarked(l)', "l.topicId && (sid ? l.marks?.[sid]?.s === 'был' : Object.values(l.marks || {}).some(m => m.s === 'был'))")
change('passedTopics(pType, pId)', 'passedTopics(pType, pId, isG ? null : id)')
change("isMarked(l) && l.ownerType === ot", "Object.values(l.marks || {}).some(m => m.s === 'был') && l.ownerType === ot")
change("  const hwCheck = { s:", "  const hwChecks = JSON.parse(JSON.stringify(draft.hwChecks || {}));\n  const solution = JSON.parse(JSON.stringify(draft.hwSolution || {}));\n  const hwCheck = { s:")
change("    hwBox.append(el('div', {class:'meta', style:'font-size:12px; margin-top:8px'},", "    hwPills.style.display = ot === 'group' ? 'none' : '';\n    if (ot === 'group') { hwPrevLine.textContent = 'Прошлое ДЗ и проверка отдельно по ученикам — ниже.'; hwBox.append(el('div', {class:'meta',text:hwCheck.s ? 'Старая общая отметка группы: '+HW_LABEL[hwCheck.s]+(hwCheck.note ? ' — '+hwCheck.note : '')+'. Личные результаты заполняются отдельно.' : 'Личные результаты заполняются отдельно.'})); }\n    if (prev && ot !== 'group') hwBox.append(homeworkSolutionView(prev.hwSolution));\n    hwBox.append(el('div', {class:'meta', style:'font-size:12px; margin-top:8px'},")
change("people.length < 2", "people.length < 1")
change("      hTa.addEventListener('input', () => { cur.homework = hTa.value; });", "      hTa.addEventListener('input', () => { cur.homework = hTa.value; });\n      const check = hwChecks[st.id] || (hwChecks[st.id] = {s:null,note:''});\n      const checkSel = el('select', {onchange:e => check.s=e.target.value || null}, el('option',{value:''},'Не проверено'), ...Object.entries(HW_LABEL).map(([v,label])=>el('option',{value:v,selected:check.s===v},label)));\n      const errors = el('textarea',{placeholder:'Номер задания, ошибка ученика, что нужно повторить',oninput:e=>check.note=e.target.value}); errors.value=check.note || '';\n      const prev = prevHomework({...draft,ownerType:ot,ownerId:oid,date:dateIn.value,time:timeIn.value},st.id);\n      cur.hwSolution = cur.hwSolution || {}; ")
change("bigField('Домашнее задание', hTa))));", "bigField('Домашнее задание', hTa)),\n        homeworkSolutionEditor(cur.hwSolution),\n        el('div',{text:prev ? 'Проверяем: '+homeworkFor(prev,st.id) : 'Ранее выданного ДЗ нет'}),\n        prev ? homeworkSolutionView(homeworkSolutionFor(prev,st.id)) : null,\n        bigField('Проверка прошлого ДЗ',checkSel),bigField('Ошибки по заданиям',errors))); ")
change("bigField('Домашнее задание на следующий раз', hwIn),", "bigField('Домашнее задание на следующий раз', hwIn), homeworkSolutionEditor(solution),")
change("    saving = true;", "    if (homeworkUploads) { toast('Дождитесь загрузки решения PDF'); return; }\n    saving = true;")
change("result: resIn.value.trim(), homework: hwIn.value.trim(),", "result: resIn.value.trim(), homework: hwIn.value.trim(), hwSolution: solution, hwChecks,")
change("data.hwCheck = hwCheck.s ?", "data.hwCheck = ot === 'group' ? (draft.hwCheck || null) : hwCheck.s ?")
change("homework: (v.homework || '').trim()}]", "homework: (v.homework || '').trim(), hwSolution:v.hwSolution}]" )
change(".filter(([, v]) => v.result || v.homework)", ".filter(([, v]) => v.result || v.homework || v.hwSolution?.text || v.hwSolution?.fileId)")
change("JSON.stringify(marks)\n", "JSON.stringify(marks), JSON.stringify(solution), JSON.stringify(hwChecks), JSON.stringify(perData)\n")
change("l.hwCheck && l.hwCheck.s", "homeworkCheckFor(l, st.id) && homeworkCheckFor(l, st.id).s")
change("HW_LABEL[l.hwCheck.s]", "HW_LABEL[homeworkCheckFor(l, st.id).s]")
change("l.hwCheck.note", "homeworkCheckFor(l, st.id).note")
change('dropOldDrafts();\nstartTick();', (root/'source/homework.js').read_text()+'\ndropOldDrafts();\nstartTick();')
change("dateIn.addEventListener('change', renderHw);", "dateIn.addEventListener('change', renderHw);\n  dateIn.addEventListener('change', renderPer);\n  timeIn.addEventListener('change', renderHw);\n  timeIn.addEventListener('change', renderPer);")
change("cur.hwSolution = cur.hwSolution || {}; \n", "cur.hwSolution = cur.hwSolution || {};\n")
change("bigField('Ошибки по заданиям',errors))); \n", "bigField('Ошибки по заданиям',errors)));\n")
