const fs=require('node:fs'),assert=require('node:assert/strict'),{boot}=require('./dom-harness.cjs');
const html=fs.readFileSync('index.html','utf8');
function setup(){const b=boot(html),a=b.api,d=a.seed();d.students=['a','b','c'].map(id=>({id,name:'TEST '+id,cls:'8',type:'группа',groupId:'g',rate:30,duration:60,slots:[]}));d.groups=[{id:'g',name:'TEST GROUP',cls:'8',memberIds:['a','b','c'],rate:20,duration:60,slots:[]}];d.lessons=[{id:'old',date:'2026-09-01',time:'10:00',duration:60,ownerType:'group',ownerId:'g',marks:{a:{s:'был',ch:true},b:{s:'был',ch:true},c:{s:'был',ch:true}},per:{a:{result:'keep'}}}];d.payments=[{id:'p',studentId:'a',amount:60,date:'2026-09-01'}];a.setState(d);a.save('fixture');return b;}
const input=(d,label)=>d.querySelectorAll('input').find(x=>x.getAttribute('aria-label')===label);
const save=d=>d.querySelectorAll('button').find(x=>x.textContent==='Сохранить').click();
function test(n,f){f();console.log('PASS '+n)}
test('Twin discounts, standard price, individual price and old amounts survive edit and reload',()=>{let {api:a,doc}=setup();a.editGroup('g');const dlg=doc.querySelector('#formDlg');input(dlg,'Цена в группе: TEST a').value='12.5';input(dlg,'Цена в группе: TEST b').value='12.5';save(dlg);let d=a.getState();for(const id of ['a','b'])assert.equal(a.liveRate({ownerType:'group',ownerId:'g'},id),12.5);assert.equal(a.liveRate({ownerType:'group',ownerId:'g'},'c'),20);assert.equal(a.liveRate({ownerType:'student'},'a'),30);assert.equal(a.lessonSum(d.lessons[0]),60);assert.equal(d.payments[0].amount,60);assert.equal(d.lessons[0].per.a.result,'keep');const r=boot(html,{storage:{'tochka-resheniya-v2':a.getRaw()}}).api;assert.equal(r.liveRate({ownerType:'group',ownerId:'g'},'a'),12.5);assert.equal(r.lessonSum(r.getState().lessons[0]),60);});
test('Student editor stores explicit free individual lesson and group rate; clearing restores group default',()=>{const {api:a,doc}=setup();a.editStudent('a');let dlg=doc.querySelector('#formDlg');input(dlg,'Цена индивидуального занятия').value='0';input(dlg,'Персональная цена в группе').value='8';save(dlg);assert.equal(a.liveRate({ownerType:'student'},'a'),0);assert.equal(a.liveRate({ownerType:'group',ownerId:'g'},'a'),8);a.editStudent('a');dlg=doc.querySelector('#formDlg');input(dlg,'Персональная цена в группе').value='';save(dlg);assert.equal(a.liveRate({ownerType:'group',ownerId:'g'},'a'),20);assert.equal(a.liveRate({ownerType:'student'},'a'),0);});
test('Explicit zero group tariff, frozen lesson price and unrelated group preserved',()=>{const {api:a}=setup(),d=a.getState();d.students[0].groupRates={g:0,other:7};const l={ownerType:'group',ownerId:'g',marks:{a:{s:'был',ch:true}}};assert.equal(a.liveRate(l,'a'),0);a.freezeLesson(l);d.students[0].groupRates.g=11;assert.equal(a.rateFor(l,'a'),0);assert.equal(a.liveRate({ownerType:'group',ownerId:'other'},'a'),7);});
test('Invalid negative tariff rejected without changing any records',()=>{const {api:a,doc}=setup();const before=a.getRaw();a.editGroup('g');const dlg=doc.querySelector('#formDlg');input(dlg,'Цена в группе: TEST a').value='-1';save(dlg);assert.equal(a.getRaw(),before);assert(dlg.open);});
test('Legacy zero and missing prices keep their previous fallback on upgrade',()=>{const {api:a}=setup(),d=a.getState();d.students[0].rate=0;assert.equal(a.liveRate({ownerType:'student'},'a'),20);a.migrate(d);assert.equal(a.rateFor(d.lessons[0],'a'),20);});
