const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {boot}=require('./dom-harness.cjs');
const html=fs.readFileSync(path.join(__dirname,'../site/index.html'),'utf8');
const make=()=>boot(html), clone=x=>JSON.parse(JSON.stringify(x));
const result=[];
async function check(name,fn){try{await fn();result.push({name,passed:true});console.log('PASS',name)}catch(e){result.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.stack)}}
function sample(a){const d=a.seed();d.students=[{id:'s1',name:'Test',rate:10,duration:90,groupId:null,type:'индивидуально'}];d.lessons=[{id:'l1',date:'2026-09-06',time:'12:00',duration:90,ownerType:'student',ownerId:'s1',marks:{s1:{s:'был',ch:true}},materialIds:['deleted-material']}];d.materials=[{id:'m1',title:'PDF',fileId:'f1'}];return d;}
function handle(text='',opts={}){let content=text;const h={name:'backup.json',writes:0,active:0,maxActive:0,queryPermission:async()=>opts.permission||'granted',requestPermission:async()=>opts.permission||'granted',getFile:async()=>new Blob([content]),createWritable:async()=>{h.writes++;h.active++;h.maxActive=Math.max(h.active,h.maxActive);let next;return{write:async t=>{if(opts.onwrite)await opts.onwrite();if(opts.failWrite)throw Error('disk full');next=t instanceof Blob?await t.text():t},close:async()=>{if(opts.failClose)throw Error('close failure');content=opts.corrupt?'{}':next;h.active--},abort:async()=>{h.active--}}},text:()=>content};return h;}
function setup(){const b=make(),a=b.api,d=sample(a);a.setState(d);a.setFileReader(async()=>new Blob([Uint8Array.from([0,1,2,255,128,42])],{type:'application/pdf'}));return {b,a,d};}
(async()=>{
await check('All application scripts compile',()=>{for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))new vm.Script(m[1]);});
await check('Storage keys and methodical programme unchanged',()=>{const old=fs.readFileSync(path.join(__dirname,'../source/baseline.html'),'utf8');for(const pattern of [/const KEY[^\n]+/,/const FILE_DB[^\n]+/,/const AUTO_DB[^\n]+/,/const PROGRAMME[^\n]+/])assert.equal(html.match(pattern)[0],old.match(pattern)[0]);assert.ok(!html.includes('deepseekCall'));});
await check('Empty startup cannot write over recovery sources',()=>{const b=make();assert.equal(b.api.getFlags().dataUnreadable,true);assert.equal(b.api.getRaw(),null);b.api.persist(true);assert.equal(b.api.getRaw(),null);});
if(process.argv[2])await check('Real supplied copy retains all records and dangling references',()=>{const b=make(),data=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));const d=b.api.safePrepare(data);for(const k of ['students','lessons','materials','payments','routes','groups','topicBank'])assert.equal(JSON.stringify(d[k]),JSON.stringify(data[k]),k);assert.equal(d.students.length,24);assert.equal(d.lessons.length,165);});
await check('Existing browser data load without migration of keys',()=>{const {a,d}=setup();a.putRaw(JSON.stringify(d));assert.equal(a.load().students.length,1);assert.equal(a.getFlags().dataUnreadable,false);});
await check('Legacy spare loads when primary is absent',()=>{const {b,a,d}=setup();b.raw['tochka-resheniya-v2-shadow']=JSON.stringify({d});assert.equal(a.load().students.length,1);});
await check('Corrupt source remains blocked and preserved',()=>{const {b,a}=setup();a.putRaw('{broken');a.load();a.persist(true);assert.equal(a.getRaw(),'{broken');assert.equal(b.raw['svetlana-rollback-20260906:tochka-resheniya-v2'],'{broken');assert.equal(a.getFlags().dataUnreadable,true);});
await check('Full backup round trip includes exact binary content',async()=>{const {a,d}=setup();const bundle=await a.safeBundle(d);const decoded=await a.safeDecode(JSON.stringify(bundle));assert.equal(decoded.files.length,1);assert.deepEqual([...new Uint8Array(await decoded.files[0].blob.arrayBuffer())],[0,1,2,255,128,42]);assert.deepEqual(clone(decoded.data),clone(a.safePrepare(d)));});
await check('Chunked full backup restores a multi-chunk binary exactly',async()=>{const {a,d}=setup();const source=Uint8Array.from({length:7*1024*1024+1},(_,i)=>i%251);a.setFileReader(async()=>new Blob([source]));const file=await a.safeBackupBlob(d);const decoded=await a.safeDecode(await file.text());assert.deepEqual(new Uint8Array(await decoded.files[0].blob.arrayBuffer()),source);assert.ok(await a.safeSameFile(file,file));});
await check('Tampered records and tampered attachments are rejected',async()=>{const {a,d}=setup();const bundle=await a.safeBundle(d),bad=clone(bundle);bad.students[0].name='changed';await assert.rejects(a.safeDecode(JSON.stringify(bad)),/Контрольная/);bundle.__svetlanaBackup.files[0].base64='AAAA';await assert.rejects(a.safeDecode(JSON.stringify(bundle)),/Повреждено/);});
await check('Missing file aborts backup before opening writable stream',async()=>{const {a}=setup();a.setFileReader(async()=>null);const h=handle('original');a.setAuto(h);assert.equal(await a.autoSaveNow(false),false);assert.equal(h.writes,0);assert.equal(h.text(),'original');});
await check('Permission rejection leaves file untouched and reports failure',async()=>{const {a}=setup();const h=handle('original',{permission:'prompt'});a.setAuto(h);assert.equal(await a.autoSaveNow(false),false);assert.equal(h.writes,0);assert.equal(a.getFlags().autoFailed,true);});
await check('Legacy autosave handle is found in original IndexedDB',async()=>{const {b,a,d}=setup();const h=handle(JSON.stringify(d));b.win.showSaveFilePicker=async()=>h;await a.autoTx('readwrite',s=>s.put(h,'file'));await a.safeRestoreAuto();assert.equal(h.writes,1);assert.equal(a.getFlags().autoFailed,false);assert.ok(JSON.parse(h.text()).__svetlanaBackup.complete);});
await check('Full write readback succeeds and old file is retained',async()=>{const {a,d}=setup(),old=JSON.stringify(d),h=handle(old);a.setAuto(h);assert.equal(await a.autoSaveNow(false),true);assert.equal(await (await a.safeTx('readonly',s=>s.get('history')))[0].file.text(),old);assert.ok(JSON.parse(h.text()).__svetlanaBackup);assert.equal(a.getFlags().safeLastSnapshot,JSON.stringify(d));});
await check('File write and close failures never claim success',async()=>{for(const flag of ['failWrite','failClose']){const {a,d}=setup(),old=JSON.stringify(d),h=handle(old,{[flag]:true});a.setAuto(h);assert.equal(await a.autoSaveNow(false),false);assert.equal(h.text(),old);assert.equal(a.getFlags().safeLastSnapshot,null);}});
await check('Readback corruption is detected and preceding file retained',async()=>{const {a,d}=setup(),old=JSON.stringify(d),h=handle(old,{corrupt:true});a.setAuto(h);assert.equal(await a.autoSaveNow(false),false);assert.equal(await (await a.safeTx('readonly',s=>s.get('history')))[0].file.text(),old);});
await check('History quota abort prevents overwriting OneDrive file',async()=>{const {b,a,d}=setup(),old=JSON.stringify(d),h=handle(old);b.idb.control.failWrites=true;a.setAuto(h);assert.equal(await a.autoSaveNow(false),false);assert.equal(h.writes,0);assert.equal(h.text(),old);});
await check('Overlapping writes are serialized; mid-write edits stay pending',async()=>{const {a,d}=setup();let concurrent;const h=handle(JSON.stringify(d),{onwrite:async()=>{d.students[0].note='new change';concurrent=await a.autoSaveNow(false)}});a.setAuto(h);assert.equal(await a.autoSaveNow(false),true);assert.equal(concurrent,false);assert.equal(h.maxActive,1);assert.equal(a.getFlags().safeLastSnapshot,null);});
await check('Empty state cannot overwrite populated autosave file',async()=>{const {a,d}=setup(),old=JSON.stringify(d),h=handle(old);a.setState(a.seed());a.setAuto(h);assert.equal(await a.autoSaveNow(false),false);assert.equal(h.writes,0);assert.equal(h.text(),old);});
await check('Newer on-disk backup cannot be overwritten by older browser state',async()=>{const {a,d}=setup();d.updatedAt='2026-01-01T00:00:00Z';const other=clone(d);other.updatedAt='2026-09-06T00:00:00Z';const h=handle(JSON.stringify(other));a.setAuto(h);assert.equal(await a.autoSaveNow(false),false);assert.equal(h.writes,0);});
await check('Import restores blobs under fresh IDs and preserves old state',async()=>{const {b,a,d}=setup();const decoded=await a.safeDecode(JSON.stringify(await a.safeBundle(d)));a.setFileReader(null);a.setState(a.seed());await a.safeInstall(decoded);const state=a.getState();assert.equal(state.students.length,1);assert.notEqual(state.materials[0].fileId,'f1');assert.deepEqual([...new Uint8Array(await (await a.getFile(state.materials[0].fileId)).arrayBuffer())],[0,1,2,255,128,42]);assert.ok(await a.safeTx('readonly',s=>s.get('history')));assert.equal(a.getFlags().dataUnreadable,false);});
await check('Failed import leaves working state and local record intact',async()=>{const {b,a,d}=setup();a.putRaw(JSON.stringify(d));const before=a.getRaw();b.idb.control.failWrites=true;await assert.rejects(a.safeInstall({data:a.seed(),files:[]}));assert.equal(a.getRaw(),before);assert.equal(a.getState().students.length,1);});
await check('Stale tab cannot overwrite a changed primary record',()=>{const {a,d}=setup();a.putRaw(JSON.stringify(d));a.load();a.putRaw('other window');a.persist(true);assert.equal(a.getRaw(),'other window');assert.equal(a.getFlags().readOnlyTab,true);});
await check('Autosave uses a 20-second delay and bounded 60-second timer',()=>{const {b,a}=setup();const timers=[];b.ctx.setTimeout=(fn,ms)=>{timers.push(ms);return timers.length};a.setAuto(handle());a.autoSaveSoon();a.autoSaveSoon();assert.deepEqual(timers,[20000,60000,20000]);});
await check('All existing views render and recovery controls exist',()=>{const {a}=setup();for(const key of ['viewHelp','viewToday','viewPeople','viewSchedule','viewMethod','viewMaterials','viewMoney','viewReports'])assert.ok(a[key]());assert.ok(a.viewHelp().textContent.includes('История и восстановление'));});
fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify(result,null,2));if(result.some(x=>!x.passed))process.exitCode=1;
})();
