const fs=require('node:fs'),assert=require('node:assert/strict');
const {boot}=require('./dom-harness.cjs');
const html=fs.readFileSync('index.html','utf8');
function setup(){const b=boot(html),d=b.api.seed();d.students=[{id:'a',name:'TEST SCHEDULE',type:'индивидуально',duration:60,format:'офлайн',rate:10,slots:[{dow:4,time:'11:00'},{dow:0,time:'12:00'}]}];d.groups=[];d.lessons=[];d.payments=[{id:'pay',studentId:'a',amount:40}];d.dayEnd=13;b.api.setState(d);b.api.save('fixture');return b;}
function btn(b,t){const x=b.doc.querySelector('#pickDlg').querySelectorAll('button').find(n=>n.textContent===t);assert.ok(x,t);x.click();}
function test(name,fn){fn();console.log('PASS '+name)}
test('Unsorted recurring days: editing Monday preserves Friday; arbitrary afternoon minutes persist after reload',()=>{
 const b=setup(),a=b.api,o=a.getState().students[0];a.standingCard('student','a',o,false).querySelectorAll('button').find(n=>n.textContent==='Изменить').click();
 assert.equal(b.doc.querySelector('#standingTime').value,'12:00');b.doc.querySelector('#standingTime').value='15:37';btn(b,'Проверить изменения');btn(b,'Сохранить');assert.equal(o.slots[0].time,'11:00');assert.equal(o.slots[1].time,'15:37');
 const raw=a.getRaw(),c=boot(html);c.api.putRaw(raw);assert.equal(c.api.load().students[0].slots[1].time,'15:37');
});
test('Unsorted recurring days: removing Monday preserves Friday',()=>{const b=setup(),o=b.api.getState().students[0];b.api.standingCard('student','a',o,false).querySelectorAll('button').find(n=>n.textContent==='Убрать').click();b.doc.querySelector('#askDlg').querySelectorAll('button').find(n=>n.textContent==='Убрать день').click();assert.equal(o.slots.length,1);assert.equal(o.slots[0].dow,4);});
function lesson(id,date,time,extra={}){return {id,date,time,duration:60,ownerType:'student',ownerId:'a',auto:true,marks:{},note:'KEEP',homework:'TASK',materialIds:['pdf'],...extra}}
test('Six months: move eligible lessons once, preserve marked/manual lessons, payments, content and undo',()=>{
 const b=setup(),a=b.api,d=a.getState(),o=d.students[0];o.slots=[{dow:0,time:'12:00'}];a.spreadSlots('student','a','2030-01-01','2030-06-30');assert.equal(d.lessons.length,25);d.lessons[0].marks={a:{s:'был',ch:true}};d.lessons[1].done=true;d.lessons[2].auto=false;d.lessons[3].time='17:00';d.lessons[4].homework='KEEP_TASK';d.lessons[4].materialIds=['PDF_KEEP'];a.save('before');const before=JSON.stringify(d);
 a.editStandingSlot('student','a',o,o.slots[0]);b.doc.querySelector('#standingTime').value='15:30';b.doc.querySelector('#standingScope').value='future';b.doc.querySelector('#standingFrom').value='2030-01-01';btn(b,'Проверить изменения');btn(b,'Сохранить');const stored=JSON.parse(a.getRaw());assert.equal(stored.lessons.length,25);assert.equal(stored.lessons.filter(l=>l.time==='15:30').length,21);assert.equal(stored.lessons[4].homework,'KEEP_TASK');assert.deepEqual(stored.lessons[4].materialIds,['PDF_KEEP']);assert.equal(stored.payments[0].amount,40);assert.equal(new Set(stored.lessons.map(l=>l.id)).size,25);a.undo();for(const key of ['students','lessons','payments'])assert.equal(JSON.stringify(a.getState()[key]),JSON.stringify(JSON.parse(before)[key]),key);
});
test('Conflicting destination blocks rule and all lesson changes',()=>{const b=setup(),a=b.api,d=a.getState(),o=d.students[0];d.lessons=[lesson('one','2030-01-07','12:00'),lesson('busy','2030-01-07','15:00',{ownerId:'b'})];const before=JSON.stringify(d);a.editStandingSlot('student','a',o,o.slots[1]);b.doc.querySelector('#standingTime').value='15:30';b.doc.querySelector('#standingScope').value='future';b.doc.querySelector('#standingFrom').value='2030-01-01';btn(b,'Проверить изменения');assert.match(b.doc.querySelector('#standingPreview').textContent,/пересечение/);btn(b,'Сохранить');assert.equal(JSON.stringify(d),before);});
test('Preview detects later edits and refuses stale commit',()=>{const b=setup(),a=b.api,d=a.getState(),o=d.students[0];a.editStandingSlot('student','a',o,o.slots[1]);b.doc.querySelector('#standingTime').value='16:10';btn(b,'Проверить изменения');d.lessons.push(lesson('new','2030-01-07','16:10'));btn(b,'Сохранить');assert.equal(o.slots[1].time,'12:00');assert.match(b.doc.querySelector('#standingPreview').textContent,/Записи изменились/);});
test('Midnight overflow and duplicate rule are rejected',()=>{const b=setup(),a=b.api,o=a.getState().students[0];a.editStandingSlot('student','a',o);b.doc.querySelector('#standingTime').value='23:30';btn(b,'Проверить изменения');assert.match(b.doc.querySelector('#standingPreview').textContent,/полуночи/);b.doc.querySelector('#standingTime').value='12:00';btn(b,'Проверить изменения');assert.match(b.doc.querySelector('#standingPreview').textContent,/пересекаются/);assert.equal(o.slots.length,2);});
test('Group move shifts weekday inside same week and respects start boundary',()=>{const b=setup(),a=b.api;const lessons=[lesson('g','2030-01-09','12:00',{ownerType:'group',ownerId:'g'})];let p=a.standingPlan('group','g',{dow:2,time:'12:00'},{dow:4,time:'16:15'},'2030-01-01',lessons);assert.equal(p.changes[0].date,'2030-01-11');assert.equal(p.conflicts.length,0);p=a.standingPlan('group','g',{dow:2,time:'12:00'},{dow:0,time:'16:15'},'2030-01-09',lessons);assert.equal(p.conflicts.length,1);});
test('Failed storage never closes editor or claims success; pending input retained',()=>{const b=setup(),a=b.api,o=a.getState().students[0];a.editStandingSlot('student','a',o,o.slots[1]);b.doc.querySelector('#standingTime').value='16:10';btn(b,'Проверить изменения');const before=a.getRaw();a.setStorageFailure(true);btn(b,'Сохранить');assert.equal(a.getRaw(),before);assert.equal(b.doc.querySelector('#pickDlg').open,true);assert.match(b.doc.querySelector('#standingPreview').textContent,/не сохранены/);});
