const fs=require('node:fs'),assert=require('node:assert/strict'),{boot}=require('./dom-harness.cjs');
const html=fs.readFileSync('index.html','utf8'),clone=x=>JSON.parse(JSON.stringify(x));
function setup(single=false){const b=boot(html),a=b.api,d=clone(a.seed());d.students=[{id:'a',name:'TEST A',cls:'8',type:'группа',groupId:'g',rate:30,individualRate:30,groupRates:{g:8},duration:60,slots:[]},{id:'ai',name:'TEST A',cls:'8',type:'индивидуально',rate:30,duration:60,slots:[]},{id:'b',name:'OTHER CHILD',cls:'8',type:'группа',groupId:'g',rate:20,duration:60,slots:[]}];d.groups=[{id:'g',name:'TEST GROUP',cls:'8',memberIds:['a','b'],rate:20,duration:60,slots:[]}];const l={date:'2026-09-01',time:'10:00',duration:60,ownerType:'group',ownerId:'g',members:['a','b'],marks:{a:{s:'был',ch:true},b:{s:'был',ch:true}},rates:{a:8,b:20},per:{a:{result:'RESULT GROUP',homework:'HW GROUP'},b:{result:'PRIVATE OTHER'}},materialIds:['PDF KEEP']};const sid=single?'a':'ai';d.lessons=[{...clone(l),id:'g1'},{...clone(l),id:'i1',date:'2026-09-02',duration:90,ownerType:'student',ownerId:sid,members:undefined,marks:{[sid]:{s:'был',ch:true}},rates:{[sid]:30},per:{[sid]:{result:'RESULT INDIVIDUAL',homework:'HW INDIVIDUAL'}}},{...clone(l),id:'miss',date:'2026-09-03',marks:{a:{s:'пропуск',ch:true}},rates:{a:8}},{...clone(l),id:'free-miss',date:'2026-09-04',marks:{a:{s:'пропуск',ch:false}},rates:{a:8}}];d.payments=[{id:'p1',studentId:'a',amount:10,date:'2026-09-02'},{id:'p2',studentId:sid,amount:10,date:'2026-09-02'},{id:'prior',studentId:'a',amount:100,date:'2026-08-01'}];d.reportNotes={'a:2026-09':'NOTE GROUP',[sid+':2026-09']:'NOTE INDIVIDUAL'};a.setState(d);a.save('fixture');return b;}
const click=(b,t)=>b.doc.querySelector('#pickDlg').querySelectorAll('button').find(x=>x.textContent===t).click();
function prepare(b,peer='ai'){b.api.editReportLink('a');b.doc.querySelector('#reportLinkPeer').value=peer;click(b,'Проверить связь');}
function link(b){prepare(b);b.doc.querySelector('#reportLinkConfirm').checked=true;click(b,'Сохранить связь');}
function test(n,f){f();console.log('PASS '+n)}
test('One card combines formats with personal fixed prices, charged absence and 60-minute hours',()=>{const b=setup(true),r=b.api.reportData('a','2026-09');assert.equal(r.charged,46);assert.equal(r.paid,20);assert.equal(r.balance,74);assert.equal(r.formats[0].charged,30);assert.equal(r.formats[0].minutes,90);assert.equal(r.formats[1].charged,16);assert.equal(r.formats[1].attended,1);assert.equal(r.formats[1].billed,2);const text=b.api.buildReport(b.api.getState().students[0],'2026-09');assert(text.includes('RESULT GROUP'));assert(text.includes('RESULT INDIVIDUAL'));assert(!text.includes('PRIVATE OTHER'));assert.match(text,/Часов занятий \(60 минут\).*2,5/);assert(!text.includes('Что освоили'));});
test('Explicit link preserves all source history, combines both notes and survives reload and backup preparation',()=>{const b=setup(),a=b.api,before=clone(a.getState());link(b);const after=clone(a.getState());for(const k of ['students','groups','lessons','payments','reportNotes','materials'])assert.deepEqual(after[k],before[k]);assert.deepEqual(after.reportPairs,[['a','ai']]);const re=boot(html,{storage:{'tochka-resheniya-v2':a.getRaw()}}).api;assert.equal(re.reportData('a','2026-09').charged,46);assert.equal(re.reportData('ai','2026-09').charged,46);assert.equal(re.reportData('a','2026-09').paid,20);assert.deepEqual(clone(re.safePrepare(after).reportPairs),[['a','ai']]);const txt=re.buildReport(re.getState().students[0],'2026-09');assert(txt.includes('NOTE GROUP'));assert(txt.includes('NOTE INDIVIDUAL'));assert(txt.includes('HW GROUP'));assert(txt.includes('HW INDIVIDUAL'));assert.equal(re.reportStudents().length,2);});
test('Matching names never create a link; archived linked source remains in report; unlinked pupil is excluded',()=>{const b=setup(),a=b.api;assert.equal(a.reportStudents().length,3);assert.equal(a.reportData('a','2026-09').charged,16);link(b);a.getState().students[1].archived=true;assert.equal(a.reportData('a','2026-09').charged,46);assert.equal(a.reportStudents().length,2);assert.equal(a.reportData('b','2026-09').charged,20);});
test('Unmarked and future lessons do not inflate month; payments-only month remains available',()=>{const b=setup(),a=b.api,d=a.getState();d.lessons.push({...clone(d.lessons[0]),id:'unmarked',marks:{},date:'2026-09-05'}, {...clone(d.lessons[0]),id:'future',date:'2099-09-01'});link(b);const r=a.reportData('a','2026-09');assert.equal(r.unmarked,1);assert.equal(r.charged,46);const zero=a.reportData('a','2026-08');assert.equal(zero.charged,0);assert.equal(zero.paid,100);const view=a.viewReports();assert(view.querySelectorAll('select').find(x=>x.getAttribute('aria-label')==='Месяц отчёта').children.some(x=>x.value==='2026-08'));});
test('Each record ID counted once; distinct equal payments both count; inconsistent copies block totals',()=>{const b=setup(),a=b.api;link(b);const d=a.getState();d.lessons.push(clone(d.lessons[0]));d.payments.push(clone(d.payments[0]));assert.equal(a.reportData('a','2026-09').charged,46);assert.equal(a.reportData('a','2026-09').paid,20);d.payments.push({...clone(d.payments[0]),amount:99});const r=a.reportData('a','2026-09');assert(r.conflicts.length);const txt=a.buildReport(d.students[0],'2026-09');assert(txt.includes('Итог не рассчитан'));assert(!txt.includes('Начислено за месяц'));});
test('Both linked cards in one lesson block creation and a later ambiguous report',()=>{const b=setup(),a=b.api,d=a.getState();d.lessons[0].members.push('ai');prepare(b);assert.match(b.doc.querySelector('#reportLinkPreview').textContent,/обе карточки/);b.doc.querySelector('#reportLinkConfirm').checked=true;click(b,'Сохранить связь');assert(!d.reportPairs);d.reportPairs=[['a','ai']];assert(a.reportData('a','2026-09').conflicts.length);assert(a.buildReport(d.students[0],'2026-09').includes('Итог не рассчитан'));});
test('Cancel, unchecked confirmation and stale preview never link cards',()=>{const b=setup(),before=b.api.getRaw();prepare(b);click(b,'Сохранить связь');assert.equal(b.api.getRaw(),before);click(b,'Отмена');assert.equal(b.api.getRaw(),before);prepare(b);b.doc.querySelector('#reportLinkConfirm').checked=true;b.api.getState().payments.push({id:'later',studentId:'a',date:'2026-09-06',amount:1});click(b,'Сохранить связь');assert.equal(b.api.getRaw(),before);assert.match(b.doc.querySelector('#reportLinkPreview').textContent,/изменились/);});
test('Unlink restores separate reports without moving history; undo restores association',()=>{const b=setup(),a=b.api;link(b);const history=clone(a.getState().lessons);prepare(b,'');b.doc.querySelector('#reportLinkConfirm').checked=true;click(b,'Сохранить связь');assert.equal(a.reportData('a','2026-09').charged,16);assert.equal(a.reportData('ai','2026-09').charged,30);assert.deepEqual(clone(a.getState().lessons),history);a.undo();assert.equal(a.reportData('a','2026-09').charged,46);});
test('Failed link save keeps durable state and pending retry; read-only blocks linking',()=>{const b=setup(),a=b.api,before=a.getRaw();prepare(b);b.doc.querySelector('#reportLinkConfirm').checked=true;a.setStorageFailure(true);click(b,'Сохранить связь');assert.equal(a.getRaw(),before);assert(b.doc.querySelector('#pickDlg').open);assert.match(b.doc.querySelector('#reportLinkPreview').textContent,/не сохранена/);a.setStorageFailure(false);a.pendingRetry();assert.equal(a.reportData('a','2026-09').charged,46);const c=setup();prepare(c);c.doc.querySelector('#reportLinkConfirm').checked=true;c.api.setFlags({readOnlyTab:true});click(c,'Сохранить связь');assert(!c.api.getState().reportPairs);});
test('Malformed, overlapping or dangling report links fail restore validation; previous versions remain accepted',()=>{const b=setup(),a=b.api,d=clone(a.getState());for(const pairs of [[['a','a']],[['a','missing']],[['a','ai'],['ai','b']],{}])assert.throws(()=>a.safePrepare({...d,reportPairs:pairs}),/связи карточек/);assert(a.safePrepare(d));});

test('Distinct lesson IDs that overlap across linked cards require review instead of double billing',()=>{const b=setup(),a=b.api;a.getState().lessons[1].date='2026-09-01';a.getState().lessons[1].time='10:30';prepare(b);assert.match(b.doc.querySelector('#reportLinkPreview').textContent,/пересекаются по времени/);assert(!a.getState().reportPairs);a.getState().reportPairs=[['a','ai']];assert(a.buildReport(a.getState().students[0],'2026-09').includes('Итог не рассчитан'));});
