const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async function(page,fixture,out,spec){
 const d=JSON.parse(JSON.stringify(fixture()));d.currency='₼';d.tutor='Тестовый репетитор';d.students[0].name='Тестовый ученик';
 const base={date:'2026-09-01',time:'10:00',duration:90,ownerType:'student',ownerId:'a',marks:{a:{s:'был',ch:true}},rates:{a:30},per:{a:{result:'Результат: разобрали дроби. Требуется повторение.',homework:'Упражнение № 12'}},note:'PRIVATE INTERNAL',materialIds:[]};
 d.lessons=[{...structuredClone(base),id:'test-individual'},{...structuredClone(base),id:'test-group',date:'2026-09-02',ownerType:'group',ownerId:'g',members:['a','b'],rates:{a:8},per:{a:{result:'Работа над ошибками',homework:'Задание № 5'},b:{result:'PRIVATE OTHER'}}}];
 d.payments=[{id:'p',studentId:'a',date:'2026-09-02',amount:20}];d.reportNotes={'a:2026-09':'Рекомендация репетитора: повторить правила сложения дробей.'};
 async function install(){await page.evaluate(d=>localStorage.setItem('tochka-resheniya-v2',JSON.stringify(d)),d);page.removeAllListeners('dialog');page.once('dialog',x=>x.accept());await page.reload();page.removeAllListeners('dialog');if(await page.locator('#menuBtn').isVisible())await page.locator('#menuBtn').click();await page.locator('#nav button').filter({hasText:'Отчёты'}).click();await page.getByLabel('Ученик в отчётах').selectOption('a');await page.getByLabel('Месяц отчёта').selectOption('2026-09');}
 async function printed(label){const before=await page.evaluate(()=>localStorage.getItem('tochka-resheniya-v2'));const opened=page.waitForEvent('popup');await page.getByRole('button',{name:'Печать / сохранить PDF',exact:true}).click();const popup=await opened;await popup.waitForLoadState();await popup.evaluate(()=>document.fonts.ready);assert(await popup.getByRole('button',{name:'Печать / сохранить PDF',exact:true}).isEnabled());const text=await popup.locator('article').innerText();for(const s of ['Тестовый ученик','₼','38','20','Долг 18','Работа над ошибками','Рекомендация репетитора'])assert(text.includes(s),s);assert(!text.includes('PRIVATE'));assert(!text.includes('Что освоено'));await popup.emulateMedia({media:'print'});assert(await popup.locator('.print-controls').isHidden());const size=await popup.locator('article').evaluate(e=>({w:e.clientWidth,s:e.scrollWidth}));assert(size.s<=size.w+2,'Print content fits');if(spec.name==='chromium-desktop')await popup.pdf({path:path.join(out,'report-'+label+'.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true});await popup.screenshot({path:path.join(out,spec.name+'-report-'+label+'.png'),fullPage:true});await popup.close();assert.equal(await page.evaluate(()=>localStorage.getItem('tochka-resheniya-v2')),before,'Printing never changes stored data');}
 await install();assert.equal(await page.locator('.report tbody td').first().evaluate(e=>getComputedStyle(e).display),'table-cell','Report cells remain tabular on mobile');await page.locator('.report').evaluate(e=>e.scrollIntoView({block:'start'}));await page.screenshot({path:path.join(out,spec.name+'-report-screen.png')});await printed('short');
 d.reportNotes['a:2026-09']+='\n'+Array.from({length:65},(_,i)=>'Строка '+(i+1)+': подробное наблюдение репетитора о выполненном задании, трудностях и следующем шаге.').join('\n')+'\nКОНЕЦ ДЛИННОГО ОТЧЁТА';
 await install();await printed('long');
 console.log('PASS report print layout, offline currency font, long content and no mutation',spec.name);
};
