const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async function(page,fixture,out,spec){
 const d=JSON.parse(JSON.stringify(fixture()));d.students.push({...d.students[0],id:'ai',name:'TEST A INDIVIDUAL',type:'индивидуально',groupId:'',rate:30});
 const base={date:'2026-09-01',time:'10:00',duration:60,ownerType:'group',ownerId:'g',members:['a','b'],marks:{a:{s:'был',ch:true},b:{s:'был',ch:true}},rates:{a:8,b:10},per:{a:{result:'GROUP RESULT',homework:'GROUP HOMEWORK'},b:{result:'PRIVATE OTHER'}},materialIds:['KEEP PDF']};
 d.lessons=[{...structuredClone(base),id:'group-old'},{...structuredClone(base),id:'individual-old',date:'2026-09-02',duration:90,ownerType:'student',ownerId:'ai',members:undefined,marks:{ai:{s:'был',ch:true}},rates:{ai:30},per:{ai:{result:'INDIVIDUAL RESULT',homework:'INDIVIDUAL HOMEWORK'}}}];
 d.payments=[{id:'p1',studentId:'a',date:'2026-09-01',amount:10},{id:'p2',studentId:'ai',date:'2026-09-01',amount:10}];d.reportNotes={'a:2026-09':'GROUP NOTE','ai:2026-09':'INDIVIDUAL NOTE'};
 await page.evaluate(d=>localStorage.setItem('tochka-resheniya-v2',JSON.stringify(d)),d);page.removeAllListeners('dialog');page.once('dialog',x=>x.accept());await page.reload();page.removeAllListeners('dialog');
 async function reports(){const menu=page.locator('#menuBtn');if(await menu.isVisible())await menu.click();await page.locator('#nav button').filter({hasText:'Отчёты'}).click();await page.getByLabel('Ученик в отчётах').selectOption('a');await page.getByLabel('Месяц отчёта').selectOption('2026-09');}
 await reports();let text=await page.locator('#view .report').innerText();assert(text.includes('GROUP RESULT'));assert(!text.includes('INDIVIDUAL RESULT'));
 const dlg=page.locator('#pickDlg');async function prepare(){await page.getByRole('button',{name:'Карточки одного ученика',exact:true}).click();await dlg.getByLabel('Вторая карточка этого же ученика').selectOption('ai');await dlg.getByRole('button',{name:'Проверить связь',exact:true}).click();}
 await prepare();await dlg.getByRole('button',{name:'Сохранить связь',exact:true}).click();assert.match(await dlg.locator('#reportLinkPreview').innerText(),/Подтвердите/);await dlg.getByRole('button',{name:'Отмена',exact:true}).click();
 let raw=await page.evaluate(()=>JSON.parse(localStorage.getItem('tochka-resheniya-v2')));assert(!raw.reportPairs);
 await prepare();await dlg.locator('#reportLinkConfirm').check();const size=await dlg.evaluate(e=>({w:e.clientWidth,s:e.scrollWidth}));assert(size.s<=size.w+2,'Link dialog fits viewport');await page.screenshot({path:path.join(out,spec.name+'-report-link.png')});await dlg.getByRole('button',{name:'Сохранить связь',exact:true}).click();await dlg.waitFor({state:'hidden'});await page.reload();await reports();
 text=await page.locator('#view .report').innerText();for(const s of ['GROUP RESULT','INDIVIDUAL RESULT','GROUP HOMEWORK','INDIVIDUAL HOMEWORK','GROUP NOTE','INDIVIDUAL NOTE'])assert(text.includes(s),s);assert(!text.includes('PRIVATE OTHER'));assert.match(text,/Начислено за месяц.*38/);assert.match(text,/Оплачено за месяц.*20/);assert.match(text,/Долг 18/);assert(text.includes('Индивидуальные'));assert(text.includes('Групповые'));assert.equal(await page.getByLabel('Ученик в отчётах').locator('option').count(),2);
 await page.locator('#view .report').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,spec.name+'-unified-report.png')});
 raw=await page.evaluate(()=>JSON.parse(localStorage.getItem('tochka-resheniya-v2')));assert.deepEqual(raw.lessons,JSON.parse(JSON.stringify(d.lessons)));assert.deepEqual(raw.payments,d.payments);assert.deepEqual(raw.reportNotes,d.reportNotes);assert.deepEqual(raw.reportPairs,[['a','ai']]);
 await page.getByRole('button',{name:'Карточки одного ученика',exact:true}).click();await dlg.getByLabel('Вторая карточка этого же ученика').selectOption('');await dlg.getByRole('button',{name:'Проверить связь',exact:true}).click();await dlg.locator('#reportLinkConfirm').check();await dlg.getByRole('button',{name:'Сохранить связь',exact:true}).click();await dlg.waitFor({state:'hidden'});await page.reload();await reports();text=await page.locator('#view .report').innerText();assert(text.includes('GROUP RESULT'));assert(!text.includes('INDIVIDUAL RESULT'));assert.equal(await page.getByLabel('Ученик в отчётах').locator('option').count(),3);
 console.log('PASS unified report and explicit card linking',spec.name);
};
